  
version: "2"

services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: "MYSQL"
    hostname: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "mysqrootpass"
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    

  whmcs:
    image: docker-whmcs
    container_name: "WHMCS"
    hostname: whmcs
    restart: always
    depends_on:
      - mysql
    environment:
      WORKER_PROCESSES: 4
      VIRTUAL_HOST: whmcs.test
      APP_PASSWORD: userapppassword
      WHMCS_SERVER_IP: 172.18.18.1
      HTTPS: "on"
    ports:
      - 80:80
      - 2222:2222
    volumes:
      - /var/www/whmcs:/var/www/whmcs

